name: Validate Pull Request

on:
  workflow_dispatch:
  pull_request: 
    branches:
      - develop
      - master

env: 
  NODE_VERSION: 16

jobs: # list of things to do
  validate-pull-request:
    name: Validate the pull request # job name (unique id)
    runs-on: ubuntu-latest 
    steps: # list of steps      
      - uses: actions/setup-node@v2
        with:
         node-version: ${{ env.NODE_VERSION }}
         registry-url: https://registry.npmjs.org/
      - uses: actions/checkout@v2
      - run: npm ci
      - run: npm run lint
      - run: npm run build
      - run: npm run test
